# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameToolSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  use_modular_headers!
  pod "AFNetworking"
  pod "Masonry"
  pod 'lottie-ios','2.5.3'
  pod "YYKit"
  pod "Toast"

  # Pods for GameToolSDK

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
       end
    end
  end
end
