# Uncomment the next line
platform :ios, '11.0'
workspace "GameToolDemo.xcworkspace"
target 'GameToolDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for GameToolDemo
  pod 'GameToolSDK'
  
end

